// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackBot.Infrastructure.Context;

#nullable disable

namespace TrackBot.Infrastructure.Migrations
{
    [DbContext(typeof(TrackContext))]
    [Migration("20230816205715_AddTableUserLanguagePreference")]
    partial class AddTableUserLanguagePreference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackBot.Domain.Models.TrackLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEvent")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTrack")
                        .HasColumnType("datetime")
                        .HasColumnName("date_track");

                    b.Property<string>("Imei")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IMEI");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(12, 9)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(12, 9)")
                        .HasColumnName("longitude");

                    b.Property<int>("TypeSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id")
                        .HasName("PK_TackLocation_id");

                    b.ToTable("TrackLocation", (string)null);
                });

            modelBuilder.Entity("TrackBot.Domain.Models.UserLanguagePreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("language_code");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserLanguagePreference", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
